# Generated by Django 2.2.4 on 2019-08-25 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='webiste',
            new_name='website',
        ),
    ]
